apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleProject
metadata:
  name: aap-demo-project-project-$git
spec:
  repo: https://github.com/ansible/ansible-tower-samples
  branch: 
  name: aap-demo-project
  scm_type: git
  organization: Default}
  description: A new project for AAP defined by backstage
  connection_secret: awxaccess
  runner_pull_policy: IfNotPresent